/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'owner' at '2/18/15 10:13 AM' with Gradle 2.2.1
 *
 * @author owner, @date 2/18/15 10:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
